name: Link Notion Task On New Pull Request
run-name: ${{ github.actor }} created a new PR
on:
  - pull_request
    # types:
    #   - opened
    #   - reopened
jobs:
  Link-Notion-Task:
    runs-on: ubuntu-latest
    steps:
      # required for accessing files in repository.
      - uses: actions/checkout@v3

      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          repository: jhao19/haoworkflows
          ssh-key: ${{ secrets.WORKFLOWS_DEPLOY_KEY }}
          path: .github/haoworkflows

      - name: DEBUG 1
        run: |
          echo $( ls ./github/haoworkflows )

      # use composite actions
      - id: notion-task-id
        uses: .github/haoworkflows/get-notion-task-id-from-title@master
        with:
          pr-title: ${{ github.event.pull_request.title }}

      - name: DEBUG 2
        run: |
          echo $( echo ${{ steps.notion-task-id.outputs.task-id }} )
      # - uses: .github/haoworkflows/update-notion-task-github-url
      #   with:
      #     notion-api-secret: ${{ secrets.NOTION_API_SECRET }}
      #     pr-link: ${{ github.event.pull_request.html_url }}
      #     task-id: ${{ steps.notion-task-id.outputs.task-id }}

      # - name: Get Notion Task Id
      #   env:
      #     GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
      #   run: |
      #     notion_task_id=$( bash .github/scripts/get-notion-task-id-from-title.sh "${{ env.GITHUB_PR_TITLE }}" )
      #     echo "NOTION_TASK_ID=$( echo $notion_task_id )" >> $GITHUB_ENV
      # - name: Update Notion Page GitHub URL
      #   env:
      #     GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
      #   if: env.NOTION_TASK_ID != ''
      #   run: bash .github/scripts/update-notion-task-github-url.sh "${{ env.NOTION_TASK_ID }}" "${{ secrets.NOTION_API_SECRET }}" "${{ env.GITHUB_PR_URL }}"
      - name: Comment On Notion Page
        env:
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
        if: env.NOTION_TASK_ID != ''
        run: |
          comment=$( echo "New pull request for task opened: ${{ env.GITHUB_PR_URL  }}" )
          bash .github/scripts/post-notion-task-comment.sh "${{ env.NOTION_TASK_ID }}" "${{ secrets.NOTION_API_SECRET }}" "$comment"
