name: Link Notion Task On New Pull Request
run-name: ${{ github.actor }} created a new PR
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  Link-Notion-Task:
    runs-on: ubuntu-latest
    steps:
      # required for accessing files in repository.
      - uses: actions/checkout@v3

      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          repository: jhao19/haoworkflows
          ssh-key: ${{ secrets.WORKFLOWS_DEPLOY_KEY }}
          path: .github/haoworkflows

      # use composite actions
      - name: Get Notion Task Id
        id: notion-task-id
        uses: ./.github/haoworkflows/get-notion-task-id-from-title
        with:
          pr-title: ${{ github.event.pull_request.title }}

      - name: DEBUG
        run: echo $( echo ${{ steps.notion-task-id.outputs.task-id }})
      - name: Update Notion Page GitHub URL
        if: steps.notion-task-id.outputs.task-id != ''
        uses: ./.github/haoworkflows/update-notion-task-github-url
        with:
          notion-api-secret: ${{ secrets.NOTION_API_SECRET }}
          pr-link: ${{ github.event.pull_request.html_url }}
          task-id: ${{ steps.notion-task-id.outputs.task-id }}
      - name: Comment On Notion Page
        if: steps.notion-task-id.outputs.task-id != ''
        uses: ./.github/haoworkflows/post-notion-task-comment
        with:
          message: "New pull request for task opened: ${{ github.event.pull_request.html_url }}"
          notion-api-secret: ${{ secrets.NOTION_API_SECRET }}
          page-id: ${{ steps.notion-task-id.outputs.task-id }}
