name: Link Notion Task On New Pull Request
run-name: ${{ github.actor }} created a new PR

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  Link-Notion-Task:
    runs-on: ubuntu-latest
    steps:
      # required for accessing files in repository.
      - uses: actions/checkout@v3

      - name: Get composite run steps repository
        uses: actions/checkout@v3
        with:
          repository: jhao19/haoworkflows
          ssh-key: ${{ secrets.WORKFLOWS_DEPLOY_KEY }}
          path: .github/haoworkflows

      # use composite actions
      - name: Get Notion Task Id
        id: notion-task-id
        uses: ./.github/haoworkflows/get-notion-task-id-from-title
        with:
          pr-title: ${{ github.event.pull_request.title }}
