name: Link Notion Task On New Pull Request
run-name: ${{ github.actor }} created a new PR
on:
  - pull_request
    # types:
    #   - opened
    #   - reopened
jobs:
  Link-Notion-Task:
    runs-on: ubuntu-latest
    steps:
      # required for accessing files in repository.
      - uses: actions/checkout@v3

      - name: Get Notion Task Id
        env:
          GITHUB_PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          notion_task_id=$( bash .github/scripts/get-notion-task-id-from-title.sh "${{ env.GITHUB_PR_TITLE }} )
          echo 'NOTION_TASK_ID=$notion_task_id' >> $GITHUB_ENV
      - name: DEBUG
        run: echo ${{ env.NOTION_TASK_ID }}
      - name: Update Notion Page GitHub URL
        env:
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
        if: env.NOTION_TASK_ID != ''
        run: bash .github/scripts/update-notion-task-github-url.sh "${{ env.NOTION_TASK_ID }}" "${{ secrets.NOTION_API_SECRET }}" "${{ env.GITHUB_PR_URL }}"
      - name: Comment On Notion Page
        env:
          GITHUB_PR_URL: ${{ github.event.pull_request.html_url }}
        if: env.NOTION_TASK_ID != ''
        run: |
          curl --location -X POST 'https://api.notion.com/v1/comments' \
          --header 'Notion-Version: 2022-06-28' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.NOTION_API_SECRET }}' \
          --data-raw '{
            "parent": {
              "page_id": "${{ env.NOTION_TASK_ID }}"
            },
            "rich_text": [
              {
                "text": {
                  "content": "New pull request for task opened: ${{ env.GITHUB_PR_URL  }}"
                }
              }
            ]
          }'
