name: Test workflow on cr

on:
  pull_request:
    types: [ opened, synchronize ] # Whenever new changes are pushed to an existing Pull Request
    branches: [ main ] # When a Pull Request to branch `main` is opened

jobs:
  test_cr_refs:
    name: Print out refs
    runs-on: ubuntu-latest
    timeout-minutes: ${{ vars.TIMEOUT_WORKFLOW }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Test getting refs on cr
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
