name: 'Test workflow on merge to main'

on:
  push:
    branches:
      - main # Will run when a PR is merged or when a commit is made directly to the main branch

env:
  HAO_STAGE: stag

jobs:
  deploy_to_stag_environment:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        id: generate-token
        uses: healthrhythms/action-github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.HAO_CICD_APP_ID }}
          private_key: ${{ secrets.HAO_CICD_APP_KEY }}