name: Test workflow on push

on:
  push:
    branches:
      - main # Will run when a PR is merged or when a commit is made directly to the main branch

jobs:
  test_push_name:
    name: Print out tag name
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      
      - name: Test getting version without script
        id: test-release-version
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
