name: Test workflow on release
on:
  push:
    tags:
      - v*
jobs:
  test_tag_name:
    name: 'Print out tag name'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone repository'
        uses: actions/checkout@v3
      
      - name: 'Test getting version without script'
        id: test-release-version
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ github.ref_name }}
