name: '[MANUAL] Test workflow on release'

on:
  workflow_dispatch:

jobs:

  test_manual_release_refs:
    name: Print out refs
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test getting refs on manual release
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
