name: '[MANUAL] Test workflow on release'

on:
  workflow_dispatch:

jobs:

  test_manual_release_refs:
    name: Print out refs
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        id: generate-token
        uses: healthrhythms/action-github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.HAO_CICD_APP_ID }}
          private_key: ${{ secrets.HAO_CICD_APP_KEY }}

      - name: Get composite run steps repository
        uses: actions/checkout@v4
        with:
          repository: healthrhythms/hrworkflows
          token: ${{ steps.generate-token.outputs.token }}
          path: .github/hrworkflows

      - name: Test getting refs on manual release
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ github.ref_name }}
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
